# Generated by Django 3.2.5 on 2021-12-07 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id'], 'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário de Time',
                'verbose_name_plural': 'Usuários de Time',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(blank=True, through='teams.UserTeam', to=settings.AUTH_USER_MODEL),
        ),
    ]
