# Generated by Django 3.2.5 on 2021-11-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Foto')),
                ('area', models.CharField(max_length=50, verbose_name='Area')),
                ('biography', models.CharField(max_length=200, verbose_name='Biografia')),
                ('git', models.TextField(max_length=100, verbose_name='Git')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
