# Generated by Django 3.2.5 on 2021-11-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Celular'),
            preserve_default=False,
        ),
    ]
