# Generated by Django 3.2.5 on 2021-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(max_length=300, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.CharField(max_length=100, verbose_name='Git'),
        ),
    ]
