# Generated by Django 3.2.5 on 2021-12-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ['id'], 'verbose_name': 'Demanda', 'verbose_name_plural': 'Demandas'},
        ),
    ]
